name: knnlm
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - ca-certificates=2022.4.26
  - certifi=2022.5.18.1
  - cudatoolkit=10.2.89
  - faiss-gpu=1.7.1
  - intel-openmp=2021.4.0
  - ld_impl_linux-64=2.38
  - libfaiss=1.7.1
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.3
  - numpy-base=1.21.5
  - openssl=1.1.1o
  - pip=21.2.2
  - python=3.7.13
  - readline=8.1.2
  - setuptools=61.2.0
  - six=1.16.0
  - sqlite=3.38.3
  - tk=8.6.12
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.12
  - pip:
    - attrs==22.1.0
    - colorama==0.4.4
    - cython==0.29.30
    - jsonlines==3.1.0
    - numpy==1.21.6
    - portalocker==2.4.0
    - regex==2022.6.2
    - sacrebleu==2.1.0
    - tabulate==0.8.9
    - torch==1.11.0
    - typing-extensions==4.2.0

