name: atlas
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - blas=1.0
  - ca-certificates=2022.10.11
  - certifi=2022.9.24
  - cudatoolkit=11.3.1
  - faiss-gpu=1.7.2
  - intel-openmp=2021.4.0
  - ld_impl_linux-64=2.38
  - libfaiss=1.7.2
  - libffi=3.3
  - libgcc-ng=12.2.0
  - libstdcxx-ng=12.2.0
  - libuv=1.44.2
  - libzlib=1.2.12
  - llvm-openmp=14.0.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.3
  - numpy=1.23.4
  - numpy-base=1.23.4
  - openssl=1.1.1s
  - pip=22.2.2
  - python=3.8.13
  - pytorch=1.11.0
  - pytorch-mutex=1.0
  - readline=8.1.2
  - setuptools=65.5.0
  - six=1.16.0
  - sqlite=3.38.5
  - tbb=2021.7.0
  - tk=8.6.12
  - typing_extensions=4.4.0
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.12
  - pip:
    - absl-py==1.3.0
    - cachetools==5.2.0
    - charset-normalizer==2.1.1
    - click==8.1.3
    - fairscale==0.4.6
    - filelock==3.8.2
    - google-auth==2.15.0
    - google-auth-oauthlib==0.4.6
    - grpcio==1.51.1
    - huggingface-hub==0.11.1
    - idna==3.4
    - importlib-metadata==5.1.0
    - joblib==1.2.0
    - markdown==3.4.1
    - markupsafe==2.1.1
    - oauthlib==3.2.2
    - packaging==21.3
    - protobuf==3.20.3
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyparsing==3.0.9
    - pyyaml==6.0
    - regex==2022.10.31
    - requests==2.28.1
    - requests-oauthlib==1.3.1
    - rouge==1.0.1
    - rsa==4.9
    - sacremoses==0.0.53
    - tensorboard==2.11.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tokenizers==0.12.1
    - tqdm==4.64.1
    - transformers==4.18.0
    - urllib3==1.26.13
    - werkzeug==2.2.2
    - wget==3.2
    - zipp==3.11.0


