
short_train = [
    {'question': 'What is the correct explanation for why we have day and night on Earth?',
     'hypothesis': 'Earth rotating on its axis causes the cycle of day and night on [blank].',
     'context': ["Earth is a kind of planet.",
                 "A planet rotating causes cycles of day and night on that planet.",
                 "The earth rotates on its tilted axis."],
     'answer': ['Earth turns on its axis.'],
     'targets': ['earth', 'planet', 'cycle']},
    {'question': 'Which is the best plan to make the fossil fuel supply last longer?',
     'hypothesis': 'Reducing the use of electricity causes the [blank] fuel supply to last longer.',
     'context': ["Oil is used for producing electricity.",
                 "To last longer means the length of time that something lasts increases.",
                 "As the use of something decreases , the use of the source of that something will decrease.",
                 "How long something lasts is a measure of how long that something is available.",
                 "Fossil fuels are a kind of energy resource.",
                 "Oil is a kind of fossil fuel.",
                 "To decrease something means to reduce something.",
                 "As the use of a resource decreases , the length of time that resource being available will increases.",
                 "As the use of something decreases, the use of things used to produce that something decreases.",
                 "Fuel supply is a kind of resource.",
                 "A supply of something is a source of that something."],
     'answer': ['reduce electricity use'],
     'targets': ["fossil", "oil", "supply", "electricity"]},
    {'question': 'Which of these human activities in a forest has a positive effect on the ecosystem?',
     'hypothesis': 'Planting trees is a kind of [MASK] activity that has a positive effect on an ecosystem.',
     'context': ["Planting trees is sometimes a human activity.",
                 "Planting trees has a positive impact on an ecosystem.",
                 "An impact means an effect."],
     'answer': ['Planting new trees where old ones were cut down'],
     'targets': ["human", "trees"]},
    {'question': 'A wind turbine primarily uses which type of energy?',
     'hypothesis': 'A wind turbine converts wind energy into electrical energy by using mechanical [MASK] .',
     'context': ["A wind turbine converts wind energy into mechanical energy for a generator.",
                 "A generator converts mechanical energy to electrical energy."],
     'answer': ['mechanical'],
     'targets': ["energy", "wind", "generator", "electrical"]},
    {'question': 'How are a tree and grass alike?',
     'hypothesis': 'A tree and grass are alike because they both have [MASK] .',
     'context': ["A structure is a kind of feature.",
                 "Grass is a kind of green plant.",
                 "A tree is a kind of plant.",
                 "Roots are a part of a plant.",
                 "A part of a living thing is a natural structure.",
                 "If two things have the same features then those two things are alike."],
     'answer': ['Both have roots.'],
     'targets': ['roots', 'plant', 'structure']}
]


yes_no_train = [
    {'question': "Does Happy Gilmore Productions CEO own a Torah? yes or no?",
     'context': ["The CEO of Happy Gilmore Productions is Adam Sandler.",
                 "Adam Sandler's religious beliefs are Judaism. ",
                 "The Torah is the first part of the bible in Judaism."],
     'answer': 'yes'},
    {'question': 'Does frost mean that it will be a snowy day? yes or no?',
     'context': ["Frost forms regularly in areas that experience freezing temperatures and morning dew.",
                 "Frost isn't deposited from the sky like snow, it forms on the ground."],
     'answer': 'no'},
    {'question': "Is Jack Black's height enough to satisfy Coronavirus distancing? yes or no?",
     'context': ["Jack Black is 5'6\" tall.",
                 "The CDC recommends people stay 6 feet apart."],
     'answer': 'no'},
    {'question': 'Can you give at least one word from the Torah to all residents of Bunkie Louisiana? yes or no?',
     'context': ["Torah scrolls must be duplicated precisely by a trained scribe.",
                 "The Torah has a total of 8,674 words.",
                 "The population of Bunkie Louisiana is 3,939 people according to a 2018 census."],
     'answer': 'yes'},
    {'question': 'Has a tumulus been discovered on Mars? yes or no?',
     'context': ["A tumulus is a mound of earth and stones raised over a grave or graves.",
                 "A grave is a location where a dead body (typically that of a human, although sometimes that of an animal) is buried.",
                 "Mars has only been explored by unmanned spacecraft.",
                 "Evidence suggests that the planet was once significantly more habitable than it is today, but whether living organisms ever existed there remains unknown. "],
     'answer': 'no'}
]