name: flan
channels:
  - pytorch
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - antlr-python-runtime=4.9.3
  - blas=1.0
  - brotlipy=0.7.0
  - ca-certificates=2022.9.24
  - certifi=2022.9.24
  - cffi=1.14.6
  - charset-normalizer=2.0.12
  - click=8.1.3
  - colorama=0.4.5
  - cryptography=37.0.2
  - cudatoolkit=11.3.1
  - dataclasses=0.8
  - filelock=3.7.1
  - huggingface_hub=0.8.1
  - hydra-core=1.2.0
  - idna=3.3
  - importlib_metadata=4.11.4
  - importlib_resources=5.10.0
  - intel-openmp=2022.0.1
  - joblib=1.1.0
  - ld_impl_linux-64=2.38
  - libblas=3.9.0
  - libcblas=3.9.0
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - liblapack=3.9.0
  - libstdcxx-ng=11.2.0
  - libuv=1.40.0
  - mkl=2022.0.1
  - ncurses=6.3
  - numpy=1.21.6
  - omegaconf=2.2.3
  - openssl=1.1.1s
  - packaging=21.3
  - pip=21.2.2
  - pycparser=2.21
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.7.13
  - python_abi=3.7
  - pytorch=1.11.0
  - pytorch-mutex=1.0
  - pyyaml=6.0
  - readline=8.1.2
  - regex=2022.4.24
  - requests=2.28.0
  - sacremoses=0.0.53
  - setuptools=61.2.0
  - six=1.16.0
  - sqlite=3.38.5
  - tk=8.6.12
  - tqdm=4.64.0
  - typing-extensions=4.1.1
  - typing_extensions=4.1.1
  - urllib3=1.26.9
  - wheel=0.37.1
  - xz=5.2.5
  - yaml=0.2.5
  - zipp=3.8.0
  - zlib=1.2.12
  - pip:
    - aiohttp==3.8.1
    - aiosignal==1.2.0
    - async-timeout==4.0.2
    - asynctest==0.13.0
    - attrs==21.4.0
    - beautifulsoup4==4.11.1
    - blis==0.7.9
    - bpemb==0.3.3
    - catalogue==2.0.8
    - cloudpickle==2.1.0
    - confection==0.0.3
    - conllu==4.4.2
    - cycler==0.11.0
    - cymem==2.0.7
    - datasets==2.3.2
    - deprecated==1.2.13
    - dill==0.3.5.1
    - en-core-web-sm==3.4.1
    - et-xmlfile==1.1.0
    - faiss==1.5.3
    - faiss-cpu==1.6.1
    - flair==0.11.3
    - fonttools==4.33.3
    - frozenlist==1.3.0
    - fsspec==2022.5.0
    - ftfy==6.1.1
    - future==0.18.2
    - gdown==4.4.0
    - gensim==4.2.0
    - hyperopt==0.2.7
    - importlib-metadata==3.10.1
    - janome==0.4.2
    - jinja2==3.1.2
    - jsonlines==3.0.0
    - kiwisolver==1.4.3
    - konoha==4.6.5
    - langcodes==3.3.0
    - langdetect==1.0.9
    - lxml==4.9.0
    - markupsafe==2.1.1
    - matplotlib==3.5.2
    - more-itertools==8.13.0
    - mpld3==0.3
    - multidict==6.0.2
    - multiprocess==0.70.13
    - murmurhash==1.0.9
    - networkx==2.6.3
    - openai==0.23.0
    - openpyxl==3.0.10
    - overrides==3.1.0
    - pandas==1.3.5
    - pandas-stubs==1.2.0.62
    - pathy==0.6.2
    - pillow==9.1.1
    - pptree==3.1
    - preshed==3.0.8
    - py4j==0.10.9.5
    - pyarrow==8.0.0
    - pydantic==1.10.2
    - python-dateutil==2.8.2
    - pytz==2022.1
    - responses==0.18.0
    - scikit-learn==1.0.2
    - scipy==1.7.3
    - segtok==1.5.11
    - sentencepiece==0.1.95
    - smart-open==5.2.1
    - soupsieve==2.3.2.post1
    - spacy==3.4.2
    - spacy-legacy==3.0.10
    - spacy-loggers==1.0.3
    - sqlitedict==2.0.0
    - srsly==2.4.5
    - tabulate==0.8.10
    - thinc==8.1.5
    - threadpoolctl==3.1.0
    - tokenizers==0.12.1
    - transformers==4.20.1
    - typer==0.4.2
    - wasabi==0.10.1
    - wcwidth==0.2.5
    - wikipedia-api==0.5.4
    - wrapt==1.14.1
    - xxhash==3.0.0
    - yarl==1.7.2

